version: 2

sources:
  - name: h1b_staged_data  # This is the "nickname" dbt will use
    database: h1b-analytics # Your Google Project ID
    schema: h1b_staged     # Your Silver Dataset
    tables:
      - name: silver_h1b_2025 
      - name: silver_h1b_2024
      - name: silver_h1b_2023